#!/bin/bash
/bin/busybox  echo "Starting init!"
/bin/busybox  mount -t proc none /proc
/bin/busybox --install

mkdir /sys
mkdir /tmp
mkdir -p /var/lock
mount -t sysfs none /sys

# Note that this only becomes /dev on the real filesystem if udev's scripts
# are used; which they will be, but it's worth pointing out
mount -t tmpfs -o mode=0755 udev /dev
touch /dev/.initramfs-tools
mkdir /dev/.initramfs
mknod /dev/console c 5 1 
mknod /dev/null c 1 3

depmod -a

/bin/bash

# Move virtual filesystems over to the real filesystem
#mount -n -o move /sys ${rootmnt}/sys
#mount -n -o move /proc ${rootmnt}/proc

#while [ ! -x ${rootmnt}${init} ]; do
#	panic "Target filesystem doesn't have ${init}"
#done

#maybe_break init

# Unset the problematic debug variable and chain to real filesystem
#unset debug
#exec run-init ${rootmnt} ${init} "$@" <${rootmnt}/dev/console >${rootmnt}/dev/console
